version: '3.9'

services:
    app:
        container_name: app
        build:
            context: ./services/app
            dockerfile: Dockerfile
        volumes:
            - ../app:/var/www/html
        tty: true

    web:
        image: nginx:1.25-alpine
        ports:
            - "80:80"
        depends_on:
            - app
        volumes:
            - ./services/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ../app/public/media:/var/www/html/public/media
